//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangedMan_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HangedMan_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a Inicio de sesión.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string BirthDateRegister {
            get {
                return ResourceManager.GetString("BirthDateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cuenta.
        /// </summary>
        public static string buttonCreate {
            get {
                return ResourceManager.GetString("buttonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelCreateMatchButton {
            get {
                return ResourceManager.GetString("CancelCreateMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deseas cancelar la creacion de la partida? .
        /// </summary>
        public static string CancelCreateMatchMessage {
            get {
                return ResourceManager.GetString("CancelCreateMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir sin guardar los cambios?.
        /// </summary>
        public static string CancelModifyConfirmation {
            get {
                return ResourceManager.GetString("CancelModifyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar modificacion.
        /// </summary>
        public static string CancelModifyHead {
            get {
                return ResourceManager.GetString("CancelModifyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar .
        /// </summary>
        public static string CancelRegisterButton {
            get {
                return ResourceManager.GetString("CancelRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorias.
        /// </summary>
        public static string CategoriesCreateMatch {
            get {
                return ResourceManager.GetString("CategoriesCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El retador ha dejado el juego.
        /// </summary>
        public static string ChallengerLeaveMatchMessage {
            get {
                return ResourceManager.GetString("ChallengerLeaveMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion.
        /// </summary>
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha modificato tu perfil.
        /// </summary>
        public static string ConfirmationModify {
            get {
                return ResourceManager.GetString("ConfirmationModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha registrado en el juego!.
        /// </summary>
        public static string ConfirmationUserRegister {
            get {
                return ResourceManager.GetString("ConfirmationUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string CreateMatch {
            get {
                return ResourceManager.GetString("CreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string CreateMatchButton {
            get {
                return ResourceManager.GetString("CreateMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador derrotado.
        /// </summary>
        public static string DataGridColumnChallengerDefeat {
            get {
                return ResourceManager.GetString("DataGridColumnChallengerDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de la partida.
        /// </summary>
        public static string DataGridColumnDate {
            get {
                return ResourceManager.GetString("DataGridColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string DataGridColumnEmail {
            get {
                return ResourceManager.GetString("DataGridColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string DataGridColumnJoin {
            get {
                return ResourceManager.GetString("DataGridColumnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NickName.
        /// </summary>
        public static string DataGridColumnNickName {
            get {
                return ResourceManager.GetString("DataGridColumnNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ya se encuentra registrado.
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string EmailLoggin {
            get {
                return ResourceManager.GetString("EmailLoggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa un correo valido.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string EmailRegister {
            get {
                return ResourceManager.GetString("EmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string EnglishButton {
            get {
                return ResourceManager.GetString("EnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string EnglishComboItem {
            get {
                return ResourceManager.GetString("EnglishComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar el historial.
        /// </summary>
        public static string ErrorLoadingHistory {
            get {
                return ResourceManager.GetString("ErrorLoadingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar las partidas.
        /// </summary>
        public static string ErrorLoadingMatches {
            get {
                return ResourceManager.GetString("ErrorLoadingMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasena y/o email incorrectos!.
        /// </summary>
        public static string ErrorLogginMessage {
            get {
                return ResourceManager.GetString("ErrorLogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar el perfil.
        /// </summary>
        public static string ErrorModify {
            get {
                return ResourceManager.GetString("ErrorModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Titulo.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error! no se pudo registrar el usuario.
        /// </summary>
        public static string ErrorUserRegister {
            get {
                return ResourceManager.GetString("ErrorUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string ExitGameButton {
            get {
                return ResourceManager.GetString("ExitGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string FirstNameRegister {
            get {
                return ResourceManager.GetString("FirstNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo.
        /// </summary>
        public static string FullNameRegister {
            get {
                return ResourceManager.GetString("FullNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el idioma de la palabra.
        /// </summary>
        public static string GameLanguageLabel {
            get {
                return ResourceManager.GetString("GameLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El adivinador ha dejado el juego!.
        /// </summary>
        public static string GuestLeaveMatchMessage {
            get {
                return ResourceManager.GetString("GuestLeaveMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado.
        /// </summary>
        public static string HangmanTittle {
            get {
                return ResourceManager.GetString("HangmanTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string HistoryColumnDate {
            get {
                return ResourceManager.GetString("HistoryColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string HistoryColumnLanguage {
            get {
                return ResourceManager.GetString("HistoryColumnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oponente.
        /// </summary>
        public static string HistoryColumnOpponent {
            get {
                return ResourceManager.GetString("HistoryColumnOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado.
        /// </summary>
        public static string HistoryColumnResult {
            get {
                return ResourceManager.GetString("HistoryColumnResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Palabra.
        /// </summary>
        public static string HistoryColumnWord {
            get {
                return ResourceManager.GetString("HistoryColumnWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa todos los datos!.
        /// </summary>
        public static string IncompleteLogginMessage {
            get {
                return ResourceManager.GetString("IncompleteLogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string IntroButton {
            get {
                return ResourceManager.GetString("IntroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te has unido a la partida!.
        /// </summary>
        public static string JoinGameMessage {
            get {
                return ResourceManager.GetString("JoinGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al unirse a la partida.
        /// </summary>
        public static string JoinMatchErrorMessage {
            get {
                return ResourceManager.GetString("JoinMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor selecciona la fecha de tu nacimiento.
        /// </summary>
        public static string LabelBirthDateEmpty {
            get {
                return ResourceManager.GetString("LabelBirthDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva cuenta.
        /// </summary>
        public static string labelCreateNewAccount {
            get {
                return ResourceManager.GetString("labelCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tu correo electronico.
        /// </summary>
        public static string LabelEmailEmpty {
            get {
                return ResourceManager.GetString("LabelEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tus apellido paterno.
        /// </summary>
        public static string LabelFirstSurnameEmpty {
            get {
                return ResourceManager.GetString("LabelFirstSurnameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tu nombre completo.
        /// </summary>
        public static string LabelFullNameEmpty {
            get {
                return ResourceManager.GetString("LabelFullNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tu nombre de usuario.
        /// </summary>
        public static string LabelNickEmpty {
            get {
                return ResourceManager.GetString("LabelNickEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tu contraseña.
        /// </summary>
        public static string LabelPasswordEmpty {
            get {
                return ResourceManager.GetString("LabelPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor vuelve a ingresa tu contraseña.
        /// </summary>
        public static string LabelPaswwordConfirmationEmpty {
            get {
                return ResourceManager.GetString("LabelPaswwordConfirmationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos obtenidos: .
        /// </summary>
        public static string LabelPointsEarned {
            get {
                return ResourceManager.GetString("LabelPointsEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tu apellido materno.
        /// </summary>
        public static string LabelSecondSurnameEmpty {
            get {
                return ResourceManager.GetString("LabelSecondSurnameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión para continuar tu aventura.
        /// </summary>
        public static string labelSubtitle {
            get {
                return ResourceManager.GetString("labelSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tu numero de telefono .
        /// </summary>
        public static string LabelTelephoneEmpty {
            get {
                return ResourceManager.GetString("LabelTelephoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Hangedman.
        /// </summary>
        public static string labelTitle {
            get {
                return ResourceManager.GetString("labelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar partida.
        /// </summary>
        public static string LeaveMatchButton {
            get {
                return ResourceManager.GetString("LeaveMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deseas abandonar el juego? .
        /// </summary>
        public static string LeaveMatchConfirmation {
            get {
                return ResourceManager.GetString("LeaveMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas disponibles.
        /// </summary>
        public static string LobbyLabel {
            get {
                return ResourceManager.GetString("LobbyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al juego.
        /// </summary>
        public static string LogginMessage {
            get {
                return ResourceManager.GetString("LogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia Sesión.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesion.
        /// </summary>
        public static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deseas salir del juego? .
        /// </summary>
        public static string LogOutMessage {
            get {
                return ResourceManager.GetString("LogOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo siento, el invitado adivinó la palabra..
        /// </summary>
        public static string LosserChallengerMessage {
            get {
                return ResourceManager.GetString("LosserChallengerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perdiste!.
        /// </summary>
        public static string LosserMatchMessage {
            get {
                return ResourceManager.GetString("LosserMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pertida (tú abandonaste).
        /// </summary>
        public static string LostYouLeft {
            get {
                return ResourceManager.GetString("LostYouLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonada.
        /// </summary>
        public static string MatchAbandoned {
            get {
                return ResourceManager.GetString("MatchAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida creada!.
        /// </summary>
        public static string MatchCreatedMessage {
            get {
                return ResourceManager.GetString("MatchCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial.
        /// </summary>
        public static string MatchHistoryButton {
            get {
                return ResourceManager.GetString("MatchHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de Partidas.
        /// </summary>
        public static string MatchHistoryLabel {
            get {
                return ResourceManager.GetString("MatchHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incompleto.
        /// </summary>
        public static string MatchIncomplete {
            get {
                return ResourceManager.GetString("MatchIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma de la partida.
        /// </summary>
        public static string MatchLanguage {
            get {
                return ResourceManager.GetString("MatchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has abandonado la partida.
        /// </summary>
        public static string MatchLeaveMessage {
            get {
                return ResourceManager.GetString("MatchLeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al abandonar la partida.
        /// </summary>
        public static string MatchLeaveMessageError {
            get {
                return ResourceManager.GetString("MatchLeaveMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perdida.
        /// </summary>
        public static string MatchLost {
            get {
                return ResourceManager.GetString("MatchLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganada.
        /// </summary>
        public static string MatchWon {
            get {
                return ResourceManager.GetString("MatchWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string ModifyProfileButton {
            get {
                return ResourceManager.GetString("ModifyProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor comprueba tu nombre completo y no uses acentos.
        /// </summary>
        public static string NamesNotValid {
            get {
                return ResourceManager.GetString("NamesNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname ya se encuentra registrado.
        /// </summary>
        public static string NicknameAlreadyRegistered {
            get {
                return ResourceManager.GetString("NicknameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa un nickname valido, solo puede contener letras y numeros.
        /// </summary>
        public static string NicknameNotValid {
            get {
                return ResourceManager.GetString("NicknameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string NickNameRegister {
            get {
                return ResourceManager.GetString("NickNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay partidas disponibles actualmente. ¡Sé el primero en crear una!.
        /// </summary>
        public static string NoMatchesAvailable {
            get {
                return ResourceManager.GetString("NoMatchesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contrasena.
        /// </summary>
        public static string PasswordConfirmationRegister {
            get {
                return ResourceManager.GetString("PasswordConfirmationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden!.
        /// </summary>
        public static string PasswordDoesntMatch {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordLoggin {
            get {
                return ResourceManager.GetString("PasswordLoggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe de tener entre 8 y 15 caracteres y solo puede contener letras y numeros.
        /// </summary>
        public static string PasswordNotValid {
            get {
                return ResourceManager.GetString("PasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordRegister {
            get {
                return ResourceManager.GetString("PasswordRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa un telefono valido.
        /// </summary>
        public static string PhoneNotValid {
            get {
                return ResourceManager.GetString("PhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de telefono.
        /// </summary>
        public static string PhoneNumberRegister {
            get {
                return ResourceManager.GetString("PhoneNumberRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro jugador se ha unido!.
        /// </summary>
        public static string PlayerJoinedMessage {
            get {
                return ResourceManager.GetString("PlayerJoinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu perfil del jugador.
        /// </summary>
        public static string ProfileViewLabel {
            get {
                return ResourceManager.GetString("ProfileViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tiene una cuenta? Regístrese aquí.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string SecondNameRegister {
            get {
                return ResourceManager.GetString("SecondNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la palabra .
        /// </summary>
        public static string SelectWordCreateMatch {
            get {
                return ResourceManager.GetString("SelectWordCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espanol.
        /// </summary>
        public static string SpanishButton {
            get {
                return ResourceManager.GetString("SpanishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espanol.
        /// </summary>
        public static string SpanishComboItem {
            get {
                return ResourceManager.GetString("SpanishComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string SpanishLanguage {
            get {
                return ResourceManager.GetString("SpanishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El telefono ya se encuentra registrado.
        /// </summary>
        public static string TelephoneAlreadyRegistered {
            get {
                return ResourceManager.GetString("TelephoneAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        public static string TelephoneRegister {
            get {
                return ResourceManager.GetString("TelephoneRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego ahorcado.
        /// </summary>
        public static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma desconocido.
        /// </summary>
        public static string UnknownLanguage {
            get {
                return ResourceManager.GetString("UnknownLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes una cuenta? Crea una!.
        /// </summary>
        public static string UserRegisterLabel {
            get {
                return ResourceManager.GetString("UserRegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Perfil.
        /// </summary>
        public static string ViewProfileButton {
            get {
                return ResourceManager.GetString("ViewProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a otro jugador.
        /// </summary>
        public static string WaitGuestMessage {
            get {
                return ResourceManager.GetString("WaitGuestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando jugador.
        /// </summary>
        public static string WaitingForPlayer {
            get {
                return ResourceManager.GetString("WaitingForPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor selecciona la categoria y la palabra!.
        /// </summary>
        public static string WarningCreateMatch {
            get {
                return ResourceManager.GetString("WarningCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El invitado no adivinó la palabra..
        /// </summary>
        public static string WinnerMatchMessageChallenger {
            get {
                return ResourceManager.GetString("WinnerMatchMessageChallenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adivinaste la palabra, Ganaste!.
        /// </summary>
        public static string WinnerMatchMessageGuest {
            get {
                return ResourceManager.GetString("WinnerMatchMessageGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganada (oponente abandonó).
        /// </summary>
        public static string WonOpponentLeft {
            get {
                return ResourceManager.GetString("WonOpponentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Palabra no disponible.
        /// </summary>
        public static string WordNotAvailable {
            get {
                return ResourceManager.GetString("WordNotAvailable", resourceCulture);
            }
        }
    }
}
